# Generated by Django 5.0.6 on 2024-05-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_userkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
