# Generated by Django 5.0.6 on 2024-05-31 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_document_encrypted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserKey',
        ),
    ]
