# Generated by Django 5.0.6 on 2024-06-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_document_encryption_key_document_iv'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
